FFU-1 Delete sub attribute EP
momentum-xyz/ubercontroller pull request #11
Opened 2022-10-31 08:51 UTC by RamsesDijkstra

Change interface attribute name to make it consistent with the rest, added delete EP (bij making subattributes nil)

2022-10-31 12:43 UTC, cnaize commented on universe/node/api_space_attributes.go
> +func (n *Node) apiDeleteSpaceSubAttribute(c *gin.Context) {
please look into this EP and change your accordingly

2022-10-31 14:01 UTC, cnaize requested changes

2022-10-31 14:01 UTC, cnaize commented on universe/node/api_space_attributes.go
> +	}
please move it before parsing space id

2022-10-31 14:02 UTC, cnaize requested changes

2022-10-31 14:02 UTC, cnaize commented on universe/node/api_space_attributes.go
> +	}
fix this please

2022-10-31 14:15 UTC, RamsesDijkstra commented on universe/node/api_space_attributes.go
> +	}
moved

2022-10-31 14:18 UTC, cnaize commented on universe/node/api_space_attributes.go
> +func (n *Node) apiDeleteSpaceAttributeSubValue(c *gin.Context) {
please rename to `remove`, we use everywhere

2022-10-31 14:18 UTC, cnaize commented on universe/node/api_space_attributes.go
> +	err = space.UpdateSpaceAttributeValue(attributeID, modifyFn, true)
please check the error on the same line, you have enough space

2022-10-31 14:19 UTC, cnaize commented on universe/node/api_space_attributes.go
> +		err = errors.WithMessage(err, "Node: apiDeleteSpaceAttributeSubValue: failed to upsert space attribute")
and fix please this message

2022-10-31 14:28 UTC, cnaize requested changes

2022-10-31 14:28 UTC, cnaize commented on universe/node/api_space_attributes.go
> +	}
please change it to parse body

2022-10-31 14:32 UTC, cnaize commented on universe/node/api_space_attributes.go
> +		api.AbortRequest(c, http.StatusInternalServerError, "failed_to_upsert", err, n.log)
and here is invalid error reason

2022-10-31 14:36 UTC, RamsesDijkstra commented on universe/node/api_space_attributes.go
> +		api.AbortRequest(c, http.StatusInternalServerError, "failed_to_upsert", err, n.log)
ill make it failed_to_upsert since thats what it is calling "UpdateSpaceAttributeValue"

2022-11-01 08:21 UTC, cnaize approved these changes

2022-11-01 08:26 UTC, merged