Private Assets
momentum-xyz/ubercontroller pull request #167
Opened 2023-05-26 17:30 UTC by dmitry-yudakov

- [ ] Keep userID and is_private for asset3d
- [ ] Allow several assets with same asset_3d_id but different user_id
- [ ] API
- [ ] Seed data

2023-06-05 07:51 UTC, jor-rit approved these changes

2023-06-05 07:51 UTC, jor-rit commented on README.md
+42 bonus points for updating Readme! ;p

2023-06-05 07:51 UTC, jor-rit commented on database/assets_3d/db.go
> +// }
just delete the commented out func

2023-06-05 07:51 UTC, jor-rit commented on universe/assets_3d/api.go
> +			// assets3d.GET("/options", a.apiGetAssets3dOptions)
again, just delete 'em. We have git history if these ever need to come back :)

2023-06-05 07:51 UTC, jor-rit commented on universe/assets_3d/assets_3d.go
> +func (a *Assets3d) CreateAsset3dIfMissing(asset3dID umid.UMID) (universe.Asset3d, error, bool) {
Not a blocker, but I'd say just `CreateAsset3d` here as the public interface name, document the return bool as 'created' and users should get the intent.

2023-06-05 07:51 UTC, jor-rit commented on universe/assets_3d/api_assets_3d.go
> +			fmt.Printf("asset3d is nil, strange! %+v\n", userAsset3d.GetAssetUserIDPair())
log.Debugf

2023-06-05 07:51 UTC, jor-rit commented on universe/assets_3d/api_assets_3d.go
> +	fmt.Printf("Upload to mm response: %+v\n", response)
delete, or log.Debugf if you really really want it (but just use debugger breakpoint I'd suggest :)

2023-06-05 08:17 UTC, dmitry-yudakov commented on universe/assets_3d/api_assets_3d.go
> +	fmt.Printf("Upload to mm response: %+v\n", response)
Yeah, sorry about these - some leftovers :)

2023-06-05 11:03 UTC, dmitry-yudakov commented on universe/assets_3d/assets_3d.go
> +func (a *Assets3d) CreateAsset3dIfMissing(asset3dID umid.UMID) (universe.Asset3d, error, bool) {
There is a simpler and more standard CreateAsset3d, hence CreateAsset3dIfMissing :)
But yeah, one of them is enough, so removed the old one and renamed the new one to CreateAsset3d.

2023-06-05 11:46 UTC, jor-rit approved these changes

2023-06-05 13:00 UTC, jor-rit requested changes

2023-06-05 13:00 UTC, jor-rit commented on universe/user_asset_3d/user_asset_3d.go
> +	defer a.mu.Unlock()
Should be a read lock, mu.RLock/RUnlock here

2023-06-06 09:01 UTC, jor-rit approved these changes

2023-06-06 09:02 UTC, merged