feature/ALP-32/verify-user-middleware
momentum-xyz/ubercontroller pull request #47
Opened 2022-12-20 15:58 UTC by RamsesDijkstra

The Parse() method also includes verfication of the token. I have created a separate function to fetch JWT secret, and have removed a bunch of duplicate code.

2022-12-20 16:12 UTC, cnaize requested changes
- looks like we don't need apiParseJWT(), is it used anywhere?
- ValidateJWT() is good, but not perfect, because we call VerifyUser() for each call for almost all EPs and in your PR it calls GetJWTSecret() each time under the hood. I suggest to add ValidateJWTWithSecret(secret) method and cache the secret inside VerifyUser()

2022-12-21 09:04 UTC, terbooter approved these changes

2022-12-21 11:23 UTC, cnaize requested changes

2022-12-21 11:23 UTC, cnaize commented on universe/common/api/middleware/verify_user.go
> +var secretStore = generic.NewSyncMap[string, *[]byte](0)
for me it's a bit complicated
I suggest just load the secret into private variable in VerifyUser() before returning gin.HandlerFunc

2022-12-21 14:28 UTC, cnaize requested changes

2022-12-21 14:28 UTC, cnaize commented on universe/common/api/middleware/verify_user.go
> +var secret *[]byte = nil
you don't need pointer here, because slice is a pointer itself

2022-12-21 14:28 UTC, cnaize commented on universe/common/api/middleware/verify_user.go
> +var secret *[]byte = nil
anyway let's move it to VerifyUser(), it's not a big deal to get secret few time while node loading

2022-12-21 14:45 UTC, cnaize requested changes

2022-12-21 14:45 UTC, cnaize commented on universe/common/api/middleware/verify_user.go
>  		}
please keep only this part, you don't need others

2022-12-21 14:45 UTC, cnaize commented on universe/common/api/middleware/verify_user.go
> +			err = errors.WithMessage(err, "failed to fetch jwt secret")
please add "Middleware: VerifyUser: " as error prefix to clearly understand which particular part of application failed

2022-12-21 14:49 UTC, cnaize commented on universe/common/api/middleware/verify_user.go
>  		}
just add at the bottom
```
secret := []byte(jwtSecret)
```

2022-12-21 14:50 UTC, cnaize approved these changes

2022-12-21 14:51 UTC, merged